### ISSUE TITLE
Boton sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [thomas64mafut/g2-frontend#108]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario .
3. Hice click en "contact us"

## Resultado esperado

Que al hacer click me redireccione a "Contact  us".

## Resultado actual

El boton no cumple niguna accion.

## Captura

![image](https://user-images.githubusercontent.com/53904695/224089605-885f5fc1-81c8-41d2-8a3f-8f04c8b81990.png)

**Comment by thomas64mafut** [comment]
agregado un pr con el fixeo del problema!
